import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { librarySchema } from "../lib/library/validation.ts";
test("library form requires a course for restricted materials", () => {
 const input={title:"Study guide",description:"",category:"study_notes",course_id:"",audience:"course_students",reason:"New resource",content_text:"Notes"};
 assert.equal(librarySchema.safeParse(input).success,false);
 assert.equal(librarySchema.safeParse({...input,audience:"all_students"}).success,true);
});
test("admin and library permissions, publication, restoration and private storage", async () => {
 const db=new PGlite();
 try {
    await db.exec(`
      create role anon nologin; create role authenticated nologin; create role service_role nologin;
      create schema auth; create schema storage;
      create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',email text default 'test@example.test',email_confirmed_at timestamptz default now());
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth,storage to anon,authenticated;
      grant execute on function auth.uid() to anon,authenticated;
      create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);
      create function storage.foldername(text) returns text[] language sql immutable as $$ select string_to_array($1,'/') $$;
      alter table storage.objects enable row level security;
      grant select,insert,update,delete on storage.objects to authenticated;
    `);
    for (const path of ["../supabase/migrations/202609150001_foundation.sql","../supabase/seed.sql","../supabase/migrations/202609150002_admissions.sql","../supabase/migrations/202609150003_notifications.sql","../supabase/migrations/202609160001_staff_access.sql","../supabase/migrations/202609160002_admin_library.sql"]) {
      await db.exec(await readFile(new URL(path,import.meta.url),"utf8"));
    }


 const ids=[1,2,3,4,5,6].map(n=>`50000000-0000-4000-8000-00000000000${n}`);
 const [admin,system,academic,student,pending,finance]=ids;
 for(const [i,id] of ids.entries()) await db.query("insert into auth.users(id,email) values($1,$2)",[id,`library${i}@example.test`]);
 await db.query("update public.profiles set account_status='active' where id<>$1",[pending]);
 await db.query("update public.profiles set student_number='SSB-TEST-1' where id=$1",[student]);
 for(const [id,role] of [[admin,'super_admin'],[system,'system_admin'],[academic,'academic_admin'],[finance,'finance_officer']]) await db.query("insert into public.user_roles(user_id,role) values($1,$2)",[id,role]);
 const asUser=async id=>{await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]); await db.exec('set role authenticated');};
 const scalar=async(sql,args=[]) => (await db.query(sql,args)).rows[0].value;
 const payload={title:'Study guide',description:'Test guide',category:'study_notes',course_id:'',audience:'all_students',content_text:'Read these study notes.'};
 const save=async data=>scalar("select public.save_library_resource(null,0,$1::jsonb,'New study material') as value",[JSON.stringify(data)]);
 const publish=async(id,revision,status)=>db.query("select public.publish_library_resource($1,$2,$3,'Publication review')",[id,revision,status]);
 await asUser(student);
 await assert.rejects(save(payload),/Library management/);
 await assert.rejects(db.query("select * from public.admin_directory('',1)"),/Account management/);
 await assert.rejects(db.query("select public.change_account_status($1,true,'Unauthorized change')",[academic]),/Account management/);
 await asUser(system); await assert.rejects(save(payload),/Library management/);
 await assert.rejects(db.query("select public.change_account_status($1,true,'Suspend administrator')",[admin]),/Only a Super/);
 await asUser(admin);
 assert.equal((await db.query("select * from public.admin_directory('library3',1)")).rows.length,1);
 await assert.rejects(db.query("select public.change_account_status($1,true,'Self suspension')",[admin]),/own account/);
 await db.query("select public.change_account_status($1,true,'Temporarily suspended')",[pending]);
 await db.query("select public.change_account_status($1,false,'Restore prior access')",[pending]);
 assert.equal(await scalar("select account_status as value from public.profiles where id=$1",[pending]),'pending');
 const resource=await save(payload);
 await asUser(student); assert.equal((await db.query("select * from public.library_resources")).rows.length,0);
 await asUser(academic); assert.equal((await db.query("select * from public.library_resources")).rows.length,1);
 await publish(resource,1,'published');
 await assert.rejects(publish(resource,1,'archived'),/changed/);
 await asUser(student); assert.equal((await db.query("select * from public.library_resources")).rows.length,1);
 await assert.rejects(db.query("update public.library_resources set status='published'"),/permission denied/);
 await asUser(pending); assert.equal((await db.query("select * from public.library_resources")).rows.length,0);
 await asUser(finance); assert.equal((await db.query("select * from public.library_resources")).rows.length,0);
 await asUser(admin); await db.query("select public.change_account_status($1,true,'Pause library access')",[student]);
 await asUser(student); assert.equal((await db.query("select * from public.library_resources")).rows.length,0);
 await asUser(admin); await db.query("select public.change_account_status($1,false,'Restore library access')",[student]);
 await publish(resource,2,'archived');
 await asUser(student); assert.equal((await db.query("select * from public.library_resources")).rows.length,0);
 await asUser(admin);
 const course=await scalar("select id as value from public.courses limit 1");
 const restricted=await save({...payload,audience:'course_students',course_id:course}); await publish(restricted,1,'published');
 await asUser(student); assert.equal((await db.query("select * from public.library_resources")).rows.length,0);
 await db.exec('reset role');
 const university='10000000-0000-4000-8000-000000000001';
 const programme=await scalar("insert into public.programmes(university_id,name,code) values($1,'Test programme','TEST') returning id as value",[university]);
 const period=await scalar("insert into public.academic_periods(university_id,name,registration_opens,registration_closes) values($1,'Test intake','2020-01-01','2099-01-01') returning id as value",[university]);
 const application=await scalar("insert into public.applications(applicant_id,full_name,university_id,programme_id,period_id,year_of_study,phone,learning_mode) values($1,'Test student',$2,$3,$4,1,'0999999999','online') returning id as value",[student,university,programme,period]);
 await db.query("insert into public.enrolments(student_id,course_id,period_id,application_id,status) values($1,$2,$3,$4,'active')",[student,course,period,application]);
 await asUser(student); assert.equal((await db.query("select * from public.library_resources")).rows.length,1);
 await db.exec('reset role'); await db.query("update public.enrolments set status='withdrawn' where student_id=$1",[student]);
 const path=admin+'/test.pdf'; await db.query("insert into storage.objects(bucket_id,name) values('library-materials',$1)",[path]);
 await asUser(admin);
 const file=await save({...payload,content_text:'',object_path:path,mime_type:'application/pdf',size_bytes:100});
 await publish(file,1,'published');
 await asUser(student);
 assert.equal((await db.query("select * from public.library_resources")).rows.length,1);
 assert.equal((await db.query("select * from storage.objects where bucket_id='library-materials'")).rows.length,0);
 await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('library-materials','bad.pdf')"),/row-level security/);
 await asUser(admin);
 await db.query("select public.configure_organisation('Test Summit','support@example.test','Update organisation')");
 assert.equal((await db.query("select * from public.admin_notifications(1)")).rows.length,0);
 await asUser(finance); await assert.rejects(db.query("select * from public.admin_notifications(1)"),/Super Administrator/);
 await asUser(academic); await assert.rejects(db.query("select public.configure_organisation('Test Summit','support@example.test','Update organisation')"),/Super Administrator/);
 await db.exec('reset role');
 const enrolment=await scalar("select id as value from public.enrolments where student_id=$1",[student]);
 await asUser(academic);
 await assert.rejects(db.query("select public.change_enrolment_status($1,'withdrawn','active','Activate course access')",[enrolment]),/approved application/);
 await db.exec('reset role'); await db.query("update public.applications set status='approved' where id=$1",[application]);
 await asUser(academic);
 await db.query("select public.change_enrolment_status($1,'withdrawn','active','Activate course access')",[enrolment]);
 await assert.rejects(db.query("select public.change_enrolment_status($1,'withdrawn','active','Stale course update')",[enrolment]),/changed/);
 await asUser(student);
 await assert.rejects(db.query("select public.change_enrolment_status($1,'active','completed','Self completion')",[enrolment]),/permission/);
 await asUser(academic); await db.query("select public.change_enrolment_status($1,'active','completed','Completed academic course')",[enrolment]);
 await assert.rejects(db.query("select public.change_enrolment_status($1,'completed','active','Reopen completed course')",[enrolment]),/transition/);
 await db.exec('reset role');
 assert.ok(Number(await scalar("select count(*) as value from public.audit_events where table_name='library_resources'"))>=7);
 } finally { await db.close(); }
});
