import { getPublicCourses, type PublicCourse } from "@/lib/admissions/public-catalogue";
export const dynamic = "force-dynamic";
import Link from "next/link";
import {ArrowRight, CalendarDays, GraduationCap, School, ShieldCheck, Users} from "lucide-react";


function Brand(){return <div className="brand"><span className="peak">▲</span><span><b>Summit ScholarsBridge</b><small>Academic Solutions</small></span></div>}
function Public({courses}:{courses:PublicCourse[]}){return <div className="site"><header className="top"><Brand/><nav><a href="#courses">Courses</a><a href="#process">How it works</a><Link href="/tutors">Our tutors</Link><Link href="/apply-to-teach">Apply to teach</Link><a href="#contact">Contact</a></nav><div><Link className="link" href="/login/student">Log in</Link><Link className="btn gold" href="/register">Register now <ArrowRight size={17}/></Link></div></header><main>
<section className="hero"><div><span className="eyebrow">Support · Skills · Progress</span><h1>Academic support that <em>moves you forward.</em></h1><p>Structured part-time classes for university students, delivered online or face-to-face by experienced tutors.</p><div className="actions"><a className="btn teal" href="#courses">Explore courses</a><Link className="btn outline" href="/register">Create account</Link></div><small><ShieldCheck/> Registration is free. Course enrolment and payments follow admission.</small></div><aside><GraduationCap/><strong>Learn today.</strong><span>Lead tomorrow.</span><i>Mzuzu University · Online & face-to-face</i></aside></section>
<section className="trust"><div><School/><b>Mzuzu University</b><span>Initial institution</span></div><div><Users/><b>Experienced tutors</b><span>Guided support</span></div><div><CalendarDays/><b>Flexible learning</b><span>Two study modes</span></div><div><ShieldCheck/><b>Secure payments</b><span>PayChangu</span></div></section>
<section className="section" id="courses"><div className="heading"><div><span className="eyebrow">Level 1</span><h2>Build a stronger foundation</h2></div><p>Choose one or more courses and study in the mode that works for you.</p></div>{courses.length===0 && <p>Course information is temporarily unavailable. Please contact admissions.</p>}<div className="course-grid">{courses.map((c,i)=><article key={c.id}><div className={`icon i${i}`}>{c.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><span>Level {c.level}</span><h3>{c.name}</h3><p>{c.description}</p><div><small>Online</small><small>Face-to-face</small></div><Link className="course-link" href={"/courses/" + c.id}>View course <ArrowRight size={15}/></Link></article>)}</div></section>
<section className="section process" id="process"><div className="heading"><div><span className="eyebrow">Simple enrolment</span><h2>From application to class</h2></div></div><div className="steps">{[["01","Apply online"],["02","Choose courses"],["03","Confirm enrolment"],["04","Start learning"]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{["Submit your details for free.","Select your level and learning mode.","Receive approval and portal access.","Access classes, materials and support."][+x[0]-1]}</p></article>)}</div></section>
<section className="cta" id="apply"><div><span className="eyebrow">Start your journey</span><h2>Ready to strengthen your semester?</h2><p>Create a free account and get ready for online or face-to-face learning.</p></div><Link className="btn gold" href="/register">Create your account <ArrowRight size={17}/></Link></section></main><footer id="contact"><Brand/><p>St. Augustine Hall, next to St. Augustine Catholic Church</p><div><b>0989 127 308 / 0998 878 269</b><span>summitscholarsbridge@gmail.com</span></div></footer></div>}


export default async function Page(){return <Public courses={await getPublicCourses()}/>}
