begin;
-- Extends the Google Meet integration: the Calendar event's id is now
-- generated by the app (so it can be embedded in the event's own description
-- before the row exists), the event's own Calendar UI link is stored
-- alongside the Meet link, and tutors can fetch their enrolled students'
-- emails to invite as Calendar attendees. Conference/sync status columns
-- were deliberately not added: the app only stores a session after Google
-- confirms the event (and its Meet link) was created, so there is no
-- distinct "pending" or "out of sync" state to record.
alter table public.class_sessions add column google_event_html_link text;

drop function if exists public.schedule_class_session(uuid,text,text,timestamptz,timestamptz,text,text,text);

create function public.schedule_class_session(p_course_id uuid,p_topic text,p_venue text,p_starts_at timestamptz,p_ends_at timestamptz,p_meeting_link text,p_reason text,p_google_event_id text default null,p_google_event_html_link text default null,p_id uuid default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare result_id uuid;
begin
 if not exists(select 1 from public.course_tutors where course_id=p_course_id and tutor_id=auth.uid()) then raise exception 'You are not assigned to this course'; end if;
 if char_length(btrim(p_topic)) not between 2 and 200 or char_length(btrim(p_venue)) not between 2 and 200 then raise exception 'Provide a topic and venue'; end if;
 if p_ends_at <= p_starts_at then raise exception 'The class must end after it starts'; end if;
 if coalesce(char_length(btrim(p_reason)),0) not between 5 and 2000 then raise exception 'Provide a reason for this schedule change'; end if;
 if exists(select 1 from public.class_sessions where tutor_id=auth.uid() and status='scheduled' and starts_at<p_ends_at and ends_at>p_starts_at) then
  raise exception 'You already have another class scheduled in this time range';
 end if;
 if exists(select 1 from public.class_sessions where venue=btrim(p_venue) and status='scheduled' and starts_at<p_ends_at and ends_at>p_starts_at) then
  raise exception 'This venue is already booked in this time range';
 end if;
 perform set_config('app.audit_reason',btrim(p_reason),true);
 insert into public.class_sessions(id,course_id,tutor_id,topic,venue,starts_at,ends_at,meeting_link,google_event_id,google_event_html_link)
 values(coalesce(p_id,gen_random_uuid()),p_course_id,auth.uid(),btrim(p_topic),btrim(p_venue),p_starts_at,p_ends_at,nullif(btrim(coalesce(p_meeting_link,'')),''),p_google_event_id,p_google_event_html_link)
 returning id into result_id;
 return result_id;
end; $$;

revoke all on function public.schedule_class_session(uuid,text,text,timestamptz,timestamptz,text,text,text,text,uuid) from public,anon;
grant execute on function public.schedule_class_session(uuid,text,text,timestamptz,timestamptz,text,text,text,text,uuid) to authenticated;

-- Lets an assigned tutor build a Calendar invite list without a broader
-- email-reading privilege; mirrors tutor_course_roster's authorization check.
create function public.class_session_attendee_emails(p_course_id uuid)
returns table(email text)
language plpgsql security definer set search_path='' as $$
begin
 if not exists(select 1 from public.course_tutors where course_id=p_course_id and tutor_id=auth.uid()) and not private.has_role('academic_admin') then
  raise exception 'You are not assigned to this course';
 end if;
 return query select u.email from public.enrolments e
  join auth.users u on u.id=e.student_id
  where e.course_id=p_course_id and e.status<>'withdrawn' and u.email is not null;
end; $$;
revoke all on function public.class_session_attendee_emails(uuid) from public,anon;
grant execute on function public.class_session_attendee_emails(uuid) to authenticated;
commit;
